---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "10"

sudo: false
dist: trusty

addons:
  chrome: stable
  firefox: latest

cache:
  yarn: true

script:
  - yarn test
